development:
  adapter: async

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  channel_prefix: shop_production
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
